---
- name: Converge
  hosts: localhost
  become: true
  vars:
    aem_port: "4502"
    aem_username: "admin"
    aem_password: "admin"
    debug_hide: false


  pre_tasks:
    - name: get docker host ip
      become: true
      shell: |
        set -o pipefail
        /sbin/ip route | awk '/default/ { print $3 }'
      args:
        executable: /bin/bash
      register: dockerhost_ip
      changed_when: false

  tasks:
    - name: verify aem is ready
      include_role:
        name: "aem_design.aem_verify"
      vars:
        aem_port: "{{ aem_port }}"
        aem_host: "{{ dockerhost_ip.stdout }}"
        debug_hide: false
