version: "3.8"

services:

  author:
    image: aemdesign/aem:sdk-2021.3.5087
    hostname: author
    healthcheck:
      test: curl -u admin:admin --header Referer:localhost --silent --connect-timeout 5 --max-time 5 localhost:8080//system/console/bundles.json | grep -q \"state\":\"Installed\" && exit 1 || exit 0
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 1s
    ports:
      - 4502:8080
      - 30303:58242
    environment:
      - "TZ=Australia/Sydney"
      - "AEM_RUNMODE=-Dsling.run.modes=author,crx3,crx3tar,localdev"
      - "AEM_JVM_OPTS=-server -Xms248m -Xmx1524m -XX:MaxDirectMemorySize=256M -XX:+CMSClassUnloadingEnabled -Djava.awt.headless=true -Dorg.apache.felix.http.host=0.0.0.0 -Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=58242,suspend=n"
    networks:
      - default
      - author-network
      - publish-network
      - dispatcher-network

  publish:
    image: aemdesign/aem:sdk-2021.3.5087
    hostname: publish
    healthcheck:
      test: curl -u admin:admin --header Referer:localhost --silent --connect-timeout 5 --max-time 5 localhost:8080//system/console/bundles.json | grep -q \"state\":\"Installed\" && exit 1 || exit 0
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 30s
    ports:
      - 4503:8080
      - 30304:58242
    environment:
      - "TZ=Australia/Sydney"
      - "AEM_RUNMODE=-Dsling.run.modes=publish,crx3,crx3tar,localdev"
      - "AEM_JVM_OPTS=-server -Xms248m -Xmx1524m -XX:MaxDirectMemorySize=256M -XX:+CMSClassUnloadingEnabled -Djava.awt.headless=true -Dorg.apache.felix.http.host=0.0.0.0 -Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=58242,suspend=n"
    networks:
      - default
      - publish-network

  dispatcher:
    image: aemdesign/dispatcher
    hostname: dispatcher
    ports:
      - 9090:8080
      - 9433:8433
    environment:
      - "TZ=Australia/Sydney"
      - "RENDERER_PORT=4503"
      - "RENDERER_HOST=publish"
      - "DISPATCHER_CONFIG=publish"
    networks:
      - default
      - dispatcher-network

networks:
  author-network:
  publish-network:
  dispatcher-network:
